name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  tag-version:
    # Only triggered when running on main
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.create-tag.outputs.version }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - id: checkout
        name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: create-tag
        name: Tag a new version
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          VERSION_TAG=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}'`
          git tag $VERSION_TAG -a -m "Automatic version increment on push"
          git push origin $VERSION_TAG
          echo "::set-output name=version::$VERSION_TAG"

